version: '3.3'
services:
  db:
    image: postgres
    container_name: snippets-saving-postgres
    volumes: 
    
      - ./data/db:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=snippets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    restart: always
    image: snippets-saving-django
    container_name: snippets-saving-django
    build: 
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=snippets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db     
  adminer:
    image: adminer
    restart: always
    container_name: snippets-saving-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"


